export const NETINFO_SET_ISCONNECTED = 'NETINFO_SET_ISCONNECTED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
export const ACCOUNT_CHANGE_PASSWORD_REQUEST = 'ACCOUNT_CHANGE_PASSWORD_REQUEST';
export const ACCOUNT_CHANGE_PASSWORD_SUCCESS = 'ACCOUNT_CHANGE_PASSWORD_SUCCESS';
export const ACCOUNT_CHANGE_PASSWORD_FAILURE = 'ACCOUNT_CHANGE_PASSWORD_FAILURE';


export const PROJECTS_CATEGORIES_GETLIST_REQUEST = 'PROJECTS_CATEGORIES_GETLIST_REQUEST';
export const PROJECTS_CATEGORIES_GETLIST_SUCCESS = 'PROJECTS_CATEGORIES_GETLIST_SUCCESS';
export const PROJECTS_CATEGORIES_GETLIST_FAILURE = 'PROJECTS_CATEGORIES_GETLIST_FAILURE';

export const PROJECTS_GETLIST_REQUEST = 'PROJECTS_GETLIST_REQUEST';
export const PROJECTS_GETLIST_SUCCESS = 'PROJECTS_GETLIST_SUCCESS';
export const PROJECTS_GETLIST_FAILURE = 'PROJECTS_GETLIST_FAILURE';
export const PROJECTS_GETLIST_REFRESHING = 'PROJECTS_GETLIST_REFRESHING';
export const PROJECTS_GETLIST_RESET_BY_KEY = 'PROJECTS_GETLIST_RESET_BY_KEY';


export const PROJECTS_DETAIL_GET_DATA_REQUEST = 'PROJECTS_DETAIL_GET_DATA_REQUEST';
export const PROJECTS_DETAIL_GET_DATA_SUCCESS = 'PROJECTS_DETAIL_GET_DATA_SUCCESS';
export const PROJECTS_DETAIL_GET_DATA_FAILURE = 'PROJECTS_DETAIL_GET_DATA_FAILURE';
export const PROJECTS_DETAIL_RESET_BY_KEY = 'PROJECTS_DETAIL_RESET_BY_KEY';
export const PROJECTS_DETAIL_GET_ACCOUNT_REQUEST = 'PROJECTS_DETAIL_GET_ACCOUNT_REQUEST';
export const PROJECTS_DETAIL_GET_ACCOUNT_SUCCESS = 'PROJECTS_DETAIL_GET_ACCOUNT_SUCCESS';
export const PROJECTS_DETAIL_GET_ACCOUNT_FAILURE = 'PROJECTS_DETAIL_GET_ACCOUNT_FAILURE';
export const PROJECTS_DETAIL_UPDATE_STATUS_ACCOUNT_REQUEST = 'PROJECTS_DETAIL_UPDATE_STATUS_ACCOUNT_REQUEST';
export const PROJECTS_DETAIL_UPDATE_STATUS_ACCOUNT_SUCCESS = 'PROJECTS_DETAIL_UPDATE_STATUS_ACCOUNT_SUCCESS';
export const PROJECTS_DETAIL_UPDATE_STATUS_ACCOUNT_FAILURE = 'PROJECTS_DETAIL_UPDATE_STATUS_ACCOUNT_FAILURE';

export const EMPLOYEES_GETLIST_REQUEST = 'EMPLOYEES_GETLIST_REQUEST';
export const EMPLOYEES_GETLIST_SUCCESS = 'EMPLOYEES_GETLIST_SUCCESS';
export const EMPLOYEES_GETLIST_FAILURE = 'EMPLOYEES_GETLIST_FAILURE';
export const EMPLOYEES_GETLIST_REFRESHING = 'EMPLOYEES_GETLIST_REFRESHING';

